fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#md_access_access:
#    resource: "@MDAccessBundle/Controller/"
#    type:     annotation
#    prefix:   /
#login:
#    pattern:   /login
#    defaults:  { _controller: MDAccessBundle:Access:login }
#check_path:
#    pattern:   /login_check
#logout:
#    pattern:   /logout
md_debate:
  resource: "@MDDebateBundle/Resources/config/routing.yml"
  prefix:   /
_internal:
  resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
  prefix:   /_internal

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
