<?php

namespace MD\DebateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContentionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentionRepository extends EntityRepository
{
}
